--------------------------------------------------------------------------------
-- 파일명    : DEMO_RESET_Oracle18cXE.sql
-- 목적      : "이미 셋업이 끝난 DB"를 시연 녹화 직전(또는 테이크 사이사이)에 처음 상태로 되돌리기 위한
--             재세팅 스크립트. DDL_DML_DCL_Oracle18cXE.sql 을 처음부터 다시 통째로 실행하면 안 된다 -
--             그 파일의 PART 1(테이블스페이스/ADC_APP·ADC_BATCH 계정/프로파일/ROLE_ADC_READONLY 롤
--             생성)은 "이미 존재하는 객체를 또 만드는" 명령이라, 이미 셋업된 DB에서 다시 돌리면
--             ORA-01543(테이블스페이스 이미 존재) / ORA-01920(사용자 이미 존재) /
--             ORA-01921(롤 이름 충돌) 같은 에러로 그 자리에서 멈춘다. 이 파일은 "테이블/계정 구조는
--             그대로 두고, 안에 든 데이터만 원래 시드 상태로 되돌리는" 용도로 새로 만들었다.
-- 실행 계정 : ADC_APP (원본 스크립트 PART 2~3, 5를 실행했던 것과 동일한 스키마 계정)
--   connect ADC_APP/ChangeMe_1234!@localhost:1521/XEPDB1
-- 사용 시점 : 시연 영상을 여러 테이크로 나눠 찍거나, 리허설 후 "방금 만든 계정/데이터"를 지우고 다시
--             깨끗한 상태에서 녹화를 시작하고 싶을 때. (예: STEP 1에서 `hong_gd`로 가입 → STEP 9~10에서
--             권한을 바꾸고 공통코드를 추가한 상태 → 다시 처음부터 찍고 싶을 때)
--------------------------------------------------------------------------------


--================================================================================
-- OPTION A. 데이터만 초기화 (권장 - 테이블 구조는 그대로 두고 데이터만 시드 상태로 되돌린다)
--   테이크 사이사이 반복 실행해도 안전하고, DDL을 다시 만들 필요가 없어 훨씬 빠르다.
--   ADC_APP 계정으로 접속해서 이 블록 전체를 그대로 실행하면 된다.
--================================================================================

--------------------------------------------------------------------------------
-- A-1. 데이터 삭제 - 자식(참조하는 쪽) 테이블부터 부모 순서로 지운다.
--   ON DELETE CASCADE가 걸린 FK도 있지만(예: ANALYSIS_DATASET→ANALYSIS_COLUMN), 걸리지 않은 FK도
--   섞여 있어서(예: REPORT_EXPORT_LOG→ANALYSIS_DATASET, NOTIFICATION_LOG→STANDARD_DOMAIN_REQUEST,
--   ANALYSIS_JOB→ANALYSIS_DATASET는 CASCADE가 없다) 캐스케이드에 기대지 않고 자식부터 명시적으로
--   전부 지우는 순서를 썼다 - 어느 쪽이든 이 순서면 FK 위반 없이 끝까지 지워진다.
--------------------------------------------------------------------------------

DELETE FROM REPORT_EXPORT_LOG;
DELETE FROM NOTIFICATION_LOG;
DELETE FROM ANALYSIS_JOB_LOG;
DELETE FROM ANALYSIS_JOB;
DELETE FROM STANDARD_DOMAIN;
DELETE FROM STANDARD_DOMAIN_REQUEST;
DELETE FROM DOMAIN_PREDICTION;
DELETE FROM ANALYSIS_COLUMN;
DELETE FROM ANALYSIS_DATASET;
DELETE FROM REFRESH_TOKEN;
DELETE FROM OAUTH_ACCOUNT;
DELETE FROM USER_ROLE;
DELETE FROM APP_USER;          -- 시연 중 가입한 hong_gd 등도 여기서 전부 같이 지워진다.
DELETE FROM DOMAIN_CODE;
DELETE FROM COMMON_CODE;       -- STEP 9에서 추가했던 DBMS_TYPE_CD 그룹의 코드도 여기서 지워진다.
DELETE FROM COMMON_CODE_GROUP; -- STEP 9에서 추가했던 DBMS_TYPE_CD 그룹 자체도 여기서 지워진다.
DELETE FROM APP_ROLE;

--------------------------------------------------------------------------------
-- A-2. IDENTITY 컬럼 채번을 처음 값으로 되돌린다.
--   Oracle의 IDENTITY 컬럼은 TRUNCATE로도 자동으로 리셋되지 않는다(PostgreSQL의
--   "TRUNCATE ... RESTART IDENTITY"에 해당하는 옵션이 없다) - ALTER TABLE ... MODIFY 로 같은
--   START WITH 값을 다시 지정해줘야 한다. 안 해줘도 시연 자체는 문제없이 돌아가지만(신청 ID가
--   1이 아니라 37부터 시작하는 정도), 여러 테이크를 찍을 때 화면에 보이는 ID 값이 매번 달라지는 걸
--   막아 녹화본끼리 비교하거나 다시 찍을 때 헷갈리지 않게 해준다.
--------------------------------------------------------------------------------

ALTER TABLE APP_USER              MODIFY USER_ID         GENERATED BY DEFAULT AS IDENTITY (START WITH 1000);
ALTER TABLE APP_ROLE               MODIFY ROLE_ID         GENERATED BY DEFAULT AS IDENTITY (START WITH 1);
ALTER TABLE OAUTH_ACCOUNT          MODIFY OAUTH_ACCOUNT_ID GENERATED BY DEFAULT AS IDENTITY (START WITH 1);
ALTER TABLE REFRESH_TOKEN          MODIFY TOKEN_ID        GENERATED BY DEFAULT AS IDENTITY (START WITH 1);
ALTER TABLE ANALYSIS_COLUMN        MODIFY COLUMN_ID       GENERATED BY DEFAULT AS IDENTITY (START WITH 1);
ALTER TABLE DOMAIN_PREDICTION      MODIFY PREDICTION_ID   GENERATED BY DEFAULT AS IDENTITY (START WITH 1);
ALTER TABLE STANDARD_DOMAIN_REQUEST MODIFY REQUEST_ID     GENERATED BY DEFAULT AS IDENTITY (START WITH 1);
ALTER TABLE ANALYSIS_JOB           MODIFY JOB_ID          GENERATED BY DEFAULT AS IDENTITY (START WITH 1);
ALTER TABLE ANALYSIS_JOB_LOG       MODIFY LOG_ID          GENERATED BY DEFAULT AS IDENTITY (START WITH 1);
ALTER TABLE NOTIFICATION_LOG       MODIFY NOTIFICATION_ID GENERATED BY DEFAULT AS IDENTITY (START WITH 1);
ALTER TABLE REPORT_EXPORT_LOG      MODIFY EXPORT_ID       GENERATED BY DEFAULT AS IDENTITY (START WITH 1);

-- DATASET_ID('DS0000000001'...)/REQUEST_NO('REQ0000000001'...)를 채번하는 시퀀스도 1부터 다시 채번되게
-- 되돌린다. Oracle 18c부터 지원하는 ALTER SEQUENCE ... RESTART 문법을 쓴다(그 이전 버전은 시퀀스를
-- DROP 후 재생성해야 했다).
ALTER SEQUENCE SEQ_DATASET_ID RESTART START WITH 1;
ALTER SEQUENCE SEQ_REQUEST_NO RESTART START WITH 1;

--------------------------------------------------------------------------------
-- A-3. 시드 데이터 재삽입 - DDL_DML_DCL_Oracle18cXE.sql의 PART 5(DML)와 완전히 동일한 내용이다.
--   원본 파일과 내용이 갈라지지 않도록, 원본 PART 5를 고치면 이 블록도 같이 고쳐야 한다.
--------------------------------------------------------------------------------

INSERT INTO COMMON_CODE_GROUP (CODE_GROUP, GROUP_NAME) VALUES ('USER_STATUS', '사용자상태');
INSERT INTO COMMON_CODE_GROUP (CODE_GROUP, GROUP_NAME) VALUES ('JOB_STATUS', '배치작업상태');
INSERT INTO COMMON_CODE_GROUP (CODE_GROUP, GROUP_NAME) VALUES ('REQUEST_STATUS', '승인요청상태');

INSERT INTO COMMON_CODE (CODE_GROUP, CODE_VALUE, CODE_NAME, SORT_ORDER) VALUES ('USER_STATUS', 'ACTIVE', '사용중', 1);
INSERT INTO COMMON_CODE (CODE_GROUP, CODE_VALUE, CODE_NAME, SORT_ORDER) VALUES ('USER_STATUS', 'LOCKED', '잠금', 2);
INSERT INTO COMMON_CODE (CODE_GROUP, CODE_VALUE, CODE_NAME, SORT_ORDER) VALUES ('USER_STATUS', 'WITHDRAWN', '탈퇴', 3);

INSERT INTO COMMON_CODE (CODE_GROUP, CODE_VALUE, CODE_NAME, SORT_ORDER) VALUES ('JOB_STATUS', 'READY', '실행전', 1);
INSERT INTO COMMON_CODE (CODE_GROUP, CODE_VALUE, CODE_NAME, SORT_ORDER) VALUES ('JOB_STATUS', 'RUNNING', '진행중', 2);
INSERT INTO COMMON_CODE (CODE_GROUP, CODE_VALUE, CODE_NAME, SORT_ORDER) VALUES ('JOB_STATUS', 'SUCCESS', '성공', 3);
INSERT INTO COMMON_CODE (CODE_GROUP, CODE_VALUE, CODE_NAME, SORT_ORDER) VALUES ('JOB_STATUS', 'INTERNAL_ERROR', '작업내부에러', 4);
INSERT INTO COMMON_CODE (CODE_GROUP, CODE_VALUE, CODE_NAME, SORT_ORDER) VALUES ('JOB_STATUS', 'CALL_ERROR', '작업호출에러', 5);

INSERT INTO COMMON_CODE (CODE_GROUP, CODE_VALUE, CODE_NAME, SORT_ORDER) VALUES ('REQUEST_STATUS', 'PENDING', '승인대기', 1);
INSERT INTO COMMON_CODE (CODE_GROUP, CODE_VALUE, CODE_NAME, SORT_ORDER) VALUES ('REQUEST_STATUS', 'APPROVED', '승인', 2);
INSERT INTO COMMON_CODE (CODE_GROUP, CODE_VALUE, CODE_NAME, SORT_ORDER) VALUES ('REQUEST_STATUS', 'REJECTED', '반려', 3);

INSERT INTO APP_ROLE (ROLE_CODE, ROLE_NAME) VALUES ('ROLE_ADMIN', '시스템 관리자');
INSERT INTO APP_ROLE (ROLE_CODE, ROLE_NAME) VALUES ('ROLE_REVIEWER', '표준 도메인 승인자');

INSERT INTO DOMAIN_CODE (DOMAIN_CODE, DOMAIN_NAME_KO, SORT_ORDER) VALUES ('ID',      'ID',     1);
INSERT INTO DOMAIN_CODE (DOMAIN_CODE, DOMAIN_NAME_KO, SORT_ORDER) VALUES ('AMOUNT',  '금액',    2);
INSERT INTO DOMAIN_CODE (DOMAIN_CODE, DOMAIN_NAME_KO, SORT_ORDER) VALUES ('DATE',    '날짜',    3);
INSERT INTO DOMAIN_CODE (DOMAIN_CODE, DOMAIN_NAME_KO, SORT_ORDER) VALUES ('CONTENT', '내용',    4);
INSERT INTO DOMAIN_CODE (DOMAIN_CODE, DOMAIN_NAME_KO, SORT_ORDER) VALUES ('NAME',    '명칭',    5);
INSERT INTO DOMAIN_CODE (DOMAIN_CODE, DOMAIN_NAME_KO, SORT_ORDER) VALUES ('NUMBER',  '번호',    6);
INSERT INTO DOMAIN_CODE (DOMAIN_CODE, DOMAIN_NAME_KO, SORT_ORDER) VALUES ('COUNT',   '수',      7);
INSERT INTO DOMAIN_CODE (DOMAIN_CODE, DOMAIN_NAME_KO, SORT_ORDER) VALUES ('CONTACT', '연락처',  8);
INSERT INTO DOMAIN_CODE (DOMAIN_CODE, DOMAIN_NAME_KO, SORT_ORDER) VALUES ('RATE',    '율',      9);
INSERT INTO DOMAIN_CODE (DOMAIN_CODE, DOMAIN_NAME_KO, SORT_ORDER) VALUES ('CODE',    '코드',   10);
INSERT INTO DOMAIN_CODE (DOMAIN_CODE, DOMAIN_NAME_KO, SORT_ORDER) VALUES ('FLAG',    '플래그', 11);

-- 비밀번호는 둘 다 평문 'Passw0rd!23'의 BCrypt 해시다.
INSERT INTO APP_USER (LOGIN_ID, PASSWORD, USER_NAME, EMAIL, DEPT_NAME, USER_STATUS)
VALUES ('admin', '$2a$10$OIQMCDHhCTi4301fsgH9TeYoKhuFUNBMHteDpS38r0lc.oLOsp2Iu', '관리자', 'admin@portfolio.dev', '데이터플랫폼팀', 'ACTIVE');

INSERT INTO APP_USER (LOGIN_ID, PASSWORD, USER_NAME, EMAIL, DEPT_NAME, USER_STATUS)
VALUES ('reviewer1', '$2a$10$OIQMCDHhCTi4301fsgH9TeYoKhuFUNBMHteDpS38r0lc.oLOsp2Iu', '김승인', 'reviewer1@portfolio.dev', '데이터거버넌스팀', 'ACTIVE');

INSERT INTO USER_ROLE (USER_ID, ROLE_ID)
SELECT U.USER_ID, R.ROLE_ID FROM APP_USER U, APP_ROLE R WHERE U.LOGIN_ID = 'admin'     AND R.ROLE_CODE = 'ROLE_ADMIN';
INSERT INTO USER_ROLE (USER_ID, ROLE_ID)
SELECT U.USER_ID, R.ROLE_ID FROM APP_USER U, APP_ROLE R WHERE U.LOGIN_ID = 'reviewer1' AND R.ROLE_CODE = 'ROLE_REVIEWER';

INSERT INTO ANALYSIS_DATASET (DATASET_ID, REQUEST_NO, DATASET_NAME, DB_SCHEMA_NAME, TABLE_NAME, DBMS_TYPE_CODE, DATASET_STATUS, REQUESTED_BY)
SELECT 'DS0000000001', 'REQ0000000001', '고객 마스터', 'SALES', 'CUSTOMER_MST', 'ORA', 'ANALYZED', U.USER_ID
FROM APP_USER U WHERE U.LOGIN_ID = 'admin';

INSERT INTO ANALYSIS_COLUMN (DATASET_ID, COLUMN_NAME, COLUMN_NAME_KO, COLUMN_NAME_EN, DATA_TYPE, DATA_LENGTH, IS_NUMERIC_YN, IS_DATE_YN, IS_UNIQUE_YN)
VALUES ('DS0000000001', 'CUST_BIRTH_DT',  '고객생년월일', 'CUST_BIRTH_DT',  'VARCHAR2', 8,  'N', 'Y', 'N');
INSERT INTO ANALYSIS_COLUMN (DATASET_ID, COLUMN_NAME, COLUMN_NAME_KO, COLUMN_NAME_EN, DATA_TYPE, DATA_LENGTH, IS_NUMERIC_YN, IS_DATE_YN, IS_UNIQUE_YN)
VALUES ('DS0000000001', 'CUST_PHONE_NO',  '고객연락처',   'CUST_PHONE_NO',  'VARCHAR2', 20, 'N', 'N', 'N');
INSERT INTO ANALYSIS_COLUMN (DATASET_ID, COLUMN_NAME, COLUMN_NAME_KO, COLUMN_NAME_EN, DATA_TYPE, DATA_LENGTH, IS_NUMERIC_YN, IS_DATE_YN, IS_UNIQUE_YN)
VALUES ('DS0000000001', 'CUST_TOT_AMT',   '고객누적금액', 'CUST_TOT_AMT',   'NUMBER',   15, 'Y', 'N', 'N');

INSERT INTO DOMAIN_PREDICTION (COLUMN_ID, DOMAIN_CODE, PREDICTION_RANK, PROBABILITY, AI_MODEL_NAME, AI_MODEL_VERSION, RESPONSE_MS, CACHE_HIT_YN)
SELECT C.COLUMN_ID, 'DATE', 1, 0.94210, 'claude-haiku', '4.5', 420, 'N'
FROM ANALYSIS_COLUMN C WHERE C.COLUMN_NAME = 'CUST_BIRTH_DT' AND C.DATASET_ID = 'DS0000000001';
INSERT INTO DOMAIN_PREDICTION (COLUMN_ID, DOMAIN_CODE, PREDICTION_RANK, PROBABILITY, AI_MODEL_NAME, AI_MODEL_VERSION, RESPONSE_MS, CACHE_HIT_YN)
SELECT C.COLUMN_ID, 'CONTACT', 1, 0.88760, 'claude-haiku', '4.5', 405, 'N'
FROM ANALYSIS_COLUMN C WHERE C.COLUMN_NAME = 'CUST_PHONE_NO' AND C.DATASET_ID = 'DS0000000001';
INSERT INTO DOMAIN_PREDICTION (COLUMN_ID, DOMAIN_CODE, PREDICTION_RANK, PROBABILITY, AI_MODEL_NAME, AI_MODEL_VERSION, RESPONSE_MS, CACHE_HIT_YN)
SELECT C.COLUMN_ID, 'AMOUNT', 1, 0.91330, 'claude-haiku', '4.5', 398, 'N'
FROM ANALYSIS_COLUMN C WHERE C.COLUMN_NAME = 'CUST_TOT_AMT' AND C.DATASET_ID = 'DS0000000001';

COMMIT;

-- 여기까지가 "OPTION A" 전체다. 이 밑으로는 실행하지 않는다 - OPTION B는 완전히 다른 상황(테이블
-- 구조 자체를 밀고 싶을 때)에서만 골라서 쓰는 별도 절차다.


--================================================================================
-- OPTION B. 테이블 구조까지 완전 초기화 (스키마 자체를 밀고 새로 만들고 싶을 때만)
--   OPTION A로 충분하면 이 블록은 필요 없다. DDL(테이블/인덱스/제약조건) 자체를 수정해서 다시 만들어야
--   할 때만 실행한다. ADC_APP 계정으로 접속해서 실행한다.
--================================================================================

--------------------------------------------------------------------------------
-- B-1. 이 스키마(ADC_APP)에 속한 오브젝트를 전부 삭제한다.
--   CASCADE CONSTRAINTS 덕분에 어느 순서로 DROP해도 FK 에러가 안 나지만, 읽기 쉽게 자식→부모 순서를
--   그대로 유지했다. PURGE를 붙여 휴지통(Recycle Bin)에도 남기지 않는다(테이블스페이스 용량이
--   빠듯한 XE 무료판이라 재활용 공간을 아끼는 게 낫다).
--------------------------------------------------------------------------------

-- DROP TABLE REPORT_EXPORT_LOG        CASCADE CONSTRAINTS PURGE;
-- DROP TABLE NOTIFICATION_LOG         CASCADE CONSTRAINTS PURGE;
-- DROP TABLE ANALYSIS_JOB_LOG         CASCADE CONSTRAINTS PURGE;
-- DROP TABLE ANALYSIS_JOB             CASCADE CONSTRAINTS PURGE;
-- DROP TABLE STANDARD_DOMAIN          CASCADE CONSTRAINTS PURGE;
-- DROP TABLE STANDARD_DOMAIN_REQUEST  CASCADE CONSTRAINTS PURGE;
-- DROP TABLE DOMAIN_PREDICTION        CASCADE CONSTRAINTS PURGE;
-- DROP TABLE DOMAIN_CODE              CASCADE CONSTRAINTS PURGE;
-- DROP TABLE ANALYSIS_COLUMN          CASCADE CONSTRAINTS PURGE;
-- DROP TABLE ANALYSIS_DATASET         CASCADE CONSTRAINTS PURGE;
-- DROP TABLE REFRESH_TOKEN            CASCADE CONSTRAINTS PURGE;
-- DROP TABLE OAUTH_ACCOUNT            CASCADE CONSTRAINTS PURGE;
-- DROP TABLE USER_ROLE                CASCADE CONSTRAINTS PURGE;
-- DROP TABLE APP_USER                 CASCADE CONSTRAINTS PURGE;
-- DROP TABLE APP_ROLE                 CASCADE CONSTRAINTS PURGE;
-- DROP TABLE COMMON_CODE              CASCADE CONSTRAINTS PURGE;
-- DROP TABLE COMMON_CODE_GROUP        CASCADE CONSTRAINTS PURGE;

-- DROP SEQUENCE SEQ_DATASET_ID;
-- DROP SEQUENCE SEQ_REQUEST_NO;

-- DROP TRIGGER TRG_ANALYSIS_DATASET_BI;

--------------------------------------------------------------------------------
-- B-2. 이제 DDL_DML_DCL_Oracle18cXE.sql 로 돌아가서 아래 부분만, 이 순서 그대로 다시 실행한다.
--
--   ✅ 다시 실행해야 하는 부분
--     - PART 2 (2-1 ~ 2-8, 시퀀스/테이블/인덱스 DDL 전체)
--     - PART 3 (업무키 자동채번 트리거)
--     - PART 4의 GRANT 문들만(오브젝트가 새로 생겼으니 ROLE_ADC_READONLY/ADC_BATCH 권한도 다시
--       걸어줘야 한다 - 동일 권한을 다시 GRANT해도 에러 없이 그냥 성공한다)
--     - PART 5 (DML 시드 데이터)
--
--   ❌ 절대 다시 실행하면 안 되는 부분
--     - PART 1 전체(테이블스페이스 TBS_ADC/TBS_ADC_TEMP, ADC_APP/ADC_BATCH 계정, ADC_PROFILE
--       프로파일) - 이 오브젝트들은 위 B-1에서 지우지 않았다(스키마 계정 자체를 지우는 게 아니라
--       그 안의 테이블만 지웠기 때문). 그대로 다시 실행하면 "이미 존재합니다" 에러가 난다.
--     - PART 4의 `CREATE ROLE ROLE_ADC_READONLY;` 한 줄 - 이 롤도 B-1에서 지우지 않았다. 이 줄만
--       빼고 GRANT 문들만 실행한다.
--------------------------------------------------------------------------------
